### ISSUE TITLE
Missing "県" in data.csv

### ISSUE THREAD

**Issue by mbasa** [kaz-ogiwara/covid19#13]
The following records have missing "県"

```
22,31,2/14,70代,男,和歌山,No.29、No.54,16名特定、健康観察実施中
39,48,2/17,40代,女,神奈川,No.27,４名特定、健康観察実施中
```

Presently, I am aggregating your data and presenting it in an interactive map, fyi:

http://geofuse.georepublic.org:80/geofuseV2/ui/showtheme?layer=csvdata.mb_1583157660253_3830&baselayer=地理院タイル(淡色地図)&color=YellowToRed&propName=col1&numRange=6&typeRange=Natural&bnd=132.7718782424927,33.201565096648864,141.0226106643677,38.84793015898388

**Comment by kaz-ogiwara** [comment]
This because the original data from MHLW has this expression.
Now it's corrected.
Thanks!
