### ISSUE TITLE
Adding English translation / サイトに英語を追加

### ISSUE THREAD

**Issue by tbkyoto** [kaz-ogiwara/covid19#14]
Can we add english translation to the site? 
I can work on editing text, but need someone to add a link on the page.

**Comment by kaz-ogiwara** [comment]
This is quite useful work... let's do it.
How can we proceed?

If you could suggest English translation,  I will create an English page and add your texts on it.
PDF, HTML, text file, or comment here... any format is fine.

**Comment by tbkyoto** [comment]
thanks.
I'll edit translations on a google sheet:
https://docs.google.com/spreadsheets/d/1ZlJedE0OpMTR-G4auJUNYJ6chNphXSZgILL-ZNbZXdk/edit?usp=sharing

**Comment by kaz-ogiwara** [comment]
Great thanks!
You also write French? That's excellent.
I'll refer it and create English and French version.

**Comment by kaz-ogiwara** [comment]
I released English version.

https://toyokeizai.net/sp/visual/tko/covid19/en.html

Please notify if you found misspelled words or weird expressions.
Thank you for your cooperation.

**Comment by tbkyoto** [comment]
looks ok to me. thank you.
I'll add french soon. Sorry you took time for english!
