### ISSUE TITLE
新型コロナウイルスの名称について

### ISSUE THREAD

**Issue by Robot-Inventor** [kaz-ogiwara/covid19#17]
# 概要
ここまで完成されているので今さら感はありますが、調べてみると、新型コロナウイルスの名称が「SARS-CoV-2」で、SARS-CoV-2による疾患が「COVID-19」のようです。

# 詳細
[国内初の新型コロナウイルスのヒト―ヒト感染事例](https://www.niid.go.jp/niid/ja/diseases/ka/corona-virus/2019-ncov/2488-idsc/iasr-news/9425-481p02.html)に、

> 新型コロナウイルス（以下、SARS-CoV-2）〜中略〜新型コロナウイルス感染症の正式名称を「COVID-19（coronavirus_ disease 2019）」と定めた（以下、COVID-19）

とあります。したがって、新型コロナウイルスの名称が「SARS-CoV-2」で、SARS-CoV-2による疾患が「COVID-19」となります。しかし、このリポジトリ内では「新型コロナウイルス=COVID-19」となってしまっています。細かいのでそのままでも問題ない気もしますが、正確性を求めると書き換えたほうが良いと思います。

**Comment by kaz-ogiwara** [comment]
対応しました。
冒頭のデスクリプションを修正しました。
ありがとうございます。
