### ISSUE TITLE
期間を選んでグラフを表示できるようにする

### ISSUE THREAD

**Issue by Robot-Inventor** [kaz-ogiwara/covid19#19]
タブレット端末で閲覧した際、患者数の推移を新規にするとグラフが細くなりすぎてグラフをタップできず、人数が見れません（PCR検査数の推移も同様）。また、ピンチアウトによる拡大もできません。そのため、グラフを表示する期間を「過去1週間」、「過去2週間」のように選べるようにすれば閲覧しやすくなると思います。
![Screenshot_2020-03-05-10-42-31](https://user-images.githubusercontent.com/50550561/75939709-52951f80-5ece-11ea-8ef5-908e177c2449.png)

**Comment by kaz-ogiwara** [comment]
ありがとうございます。
グラフを分けて表示し、グループ棒グラフ（Grouped Bar Chart）は使わないようになりました。
