### ISSUE TITLE
英語版READMEのファイル名について

### ISSUE THREAD

**Issue by rozeo** [kaz-ogiwara/covid19#22]
PullRequest #11にて追加された英語版READMEについて、メインのREADMEと比べてファイル名に一貫性がないようです。
また中身はMarkdown形式にかかわらず、.md拡張子が抜け落ちているため、Githubの仕様上サイト上で装飾がされ見にくいかと思います。

(小さい点ですがPR発行させていただきました)

**Comment by kaz-ogiwara** [comment]
PRをMergeしました。
ありがとうございます！
