### ISSUE TITLE
検査陽性者の状況　をビジュアルに表示

### ISSUE THREAD

**Issue by masayasuyamamoto60** [kaz-ogiwara/covid19#23]
コロナウイルスの深刻度を表現するために検査陽性者に関する情報を視覚化することが有効だと考える。それによってパニック行動を回避することにも効果があるはず。
現状の都のサイトでは、カテゴリーごとの人数を表示しているが、実績値を見ても全体像を把握することができない。
そこで、2種類の情報に分けることを提案する：
１．テスト被験者対陽性者
２．陽性者の現状
特に２．に関しては現状の情報表示は構造化しており、わかりにくくなっているためビジュアル化（棒ブラフ、または多層化したパイチャート）することが望まれる。
添付は、エクセルにて棒グラフ化した例
![table_sample1](https://user-images.githubusercontent.com/12755558/76137319-c24a0c80-607e-11ea-924b-e7e81cfb4df3.jpg)

**Comment by dtaniwaki** [comment]
陽性者も無症状、軽症、重症など症状で全く数字の印象が変わるので、是非お願いします！

**Comment by kaz-ogiwara** [comment]
ありがとうございます。
陽性者、患者、重症、死亡などグラフを分けて表示するようにしました。

**Comment by masayasuyamamoto60** [comment]
画面を見るのが楽しみです
