### ISSUE TITLE
"Cases by Prefectures" does not include "無症状病原体保有者"

### ISSUE THREAD

**Issue by emiddleton** [kaz-ogiwara/covid19#32]
I was comparing data with https://covid19japan.com/ which reports 146 Cases for Aichi and noticed the value 134 cases you are reporting, which appears to come from https://www.mhlw.go.jp/stf/newpage_10385.html where it says (無症状病原体保有者を除く).  If this is the reason for the discrepancy then there should be a note saying this doesn't include asymptomatic cases.

**Comment by kaz-ogiwara** [comment]
I changed data source from "With Symptoms" to "PCR tested positive".
Thanks.
