### ISSUE TITLE
data/individuals.csv の更新について

### ISSUE THREAD

**Issue by kurain** [kaz-ogiwara/covid19#34]
事後報告になってしまい申し訳ないのですが、
[都道府県別の新型コロナウィルス感染者数推移](https://kurain.github.io/covid19/) というサイトをこちらで提供の data/individuals.csv を利用して作成しております。
データの提供大変ありがとうございます。

本日はこちらのデータの更新が無いようなのですが、今後は提供されないということでしょうか。

**Comment by kaz-ogiwara** [comment]
ご連絡ありがとうございます。
はい、こちらのファイルは今後は更新されません。

元々このファイルは、厚生労働省が自治体からの報告を一括して公開しているデータを使っていました。
しかし2週間ほど前から一括公開がなくなったため、自治体の報告をすべて読んで同じ形式に合わせる、という作業を行っていました。

今般の患者数急増に伴い、作業の手間が膨大になってきたことや、最新の都道府県別患者数・感染者数は別の場所から転記できることなどを勘案して、1件ずつ自治体の報告を読むことはやめ、individuals.csvも更新を停止しています。

**Comment by kurain** [comment]
ご連絡ありがとうございます。
承知いたしました。

今までのデータ提供、誠にありがとうございました。
