### ISSUE TITLE
「各都道府県の状況」のアニメーションを都道府県選択時にOFFに

### ISSUE THREAD

**Issue by xyx-is** [kaz-ogiwara/covid19#45]
現在、「各都道府県の状況」欄には、選択中の県以外の状況が薄い青い線で表示されているので、選択している都道府県を変更したときに、毎回したから立ち上がってくるアニメーションがあるより、OFFにした方がどの線がというのが分かりやすいと思います。ご検討ください。

**Comment by kaz-ogiwara** [comment]
対応しました。
