### ISSUE TITLE
Age by year instead of by decade?

### ISSUE THREAD

**Issue by chrissaid** [kaz-ogiwara/covid19#47]
Thank you for making this data available!

Do you have access to cases or deaths by age in years? I know that [demography.csv](https://github.com/kaz-ogiwara/covid19/blob/master/data/demography.csv) has a breakdown by _age decade_, but it would be very important to look at each age year.  

Background: According to [this paper](https://www.medrxiv.org/content/10.1101/2020.03.24.20042937v1.full.pdf), Japan started the BCG vaccine in 1947. A very clear way to test the BCG hypothesis is to look for a sharp drop in cases or deaths starting in 1947.

**Comment by kaz-ogiwara** [comment]
> Do you have access to cases or deaths by age in years?
No, MHLW does not publish cases (or any data) by age in years.
