### ISSUE TITLE
4月17日以降の都道府県データから（県）

### ISSUE THREAD

**Issue by oraora2208** [kaz-ogiwara/covid19#48]

**Comment by oraora2208** [comment]
データ利用させていただいています。
1点気づいてたのですが、表題の通り4月17日以降の都道府県データから（県）、（府）などの表記が抜けているようです。

**Comment by emaruko** [comment]
こちらも自分で書いているプログラムにエラーが出て oraora2208さんの言われるような不整合があることに気が付きました。

**Comment by emaruko** [comment]
こちらも自分で書いているプログラムにエラーが出て oraora2208さんの言われるようなデータの不整合があることに気が付きました。
あと、陽性率というカラムが追加されたのですが、rawデータに必要なのだろうかと思いました。誤差が出ますし。
また、「検査人数の集計期間に対応する陽性者数」という4/17から追加された新しいカラムが具体的に何を表しているのかピンときません。

**Comment by oraora2208** [comment]
prefectures-2.csv　の4月17日以降のデータに県、都、府を足し、合計行も入っていたためそちらも削除しました。
[prefectures-2.csv.zip](https://github.com/kaz-ogiwara/covid19/files/4499912/prefectures-2.csv.zip)

**Comment by emaruko** [comment]
oraora2208さん、修正データありがとうございました。合計行も入っていたことには気づきませんでした。ありがとうございます。

**Comment by kaz-ogiwara** [comment]
コメントありがとうございます。
こちらは厚生労働省から発表されている表記に従っています。

**Comment by kaz-ogiwara** [comment]
都道府県の表記や陽性率は厚生労働省の表記に従っています。
ご利用の際は適宜調整してお使いください。
