### ISSUE TITLE
感染者数よりも患者数の方が多い

### ISSUE THREAD

**Issue by gyu-don** [kaz-ogiwara/covid19#49]
![Screenshot_20200422_102021](https://user-images.githubusercontent.com/13610313/79930164-bf667800-8482-11ea-8736-c3bf9030548e.png)

「感染者数 < 患者数」になっています。感染者数と患者数の違いに関する説明を読むと、
「感染者数 > 患者数」になるように思います。

もし患者数の方が多くなる理由がありましたら「よくあるご質問」への追記等をご検討ください。

**Comment by kaz-ogiwara** [comment]
ページをリロードしていただけますか？
正常に読み込まれていれば感染者数は21日時点で10,974名になるはずです。
もしリロードしても直らなければ対応しますのでお使いの環境を教えていただければと思います。

**Comment by gyu-don** [comment]
ありがとうございます。F5でリロードしたら直りました。
![Screenshot_20200422_230038](https://user-images.githubusercontent.com/13610313/79991130-e35ea380-84ec-11ea-8235-89e750c9b7bb.png)

念の為、環境はFirefox 75.0 (Linux)です。
Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
