### ISSUE TITLE
prefectures-2.csv: 東京の検査数が都の発表数と異なります

### ISSUE THREAD

**Issue by DudeSI** [kaz-ogiwara/covid19#50]
データの公開どうも有り難うございます。とても有用だと思います。私もデータを視覚化して現状把握に努めております。

prefectures-2.csvで東京都の累積検査数の値との発表と食い違うケースがあります。

- 日付がずれているケース(4月22日の値9124は都の発表では4月21日の値です)
- 前日と同じ値が連続するケース(4月24-26日など)

があります。ご確認頂けますでしょうか。どうぞよろしくお願い申し上げます。

**Comment by kaz-ogiwara** [comment]
ありがとうございます。
東京都が過去分の数値を訂正していたことが原因でした。
取り急ぎ現在あるデータの分は修正しましたが、今後の対応は検討します。

**Comment by DudeSI** [comment]
ご対応頂きどうも有り難うございました。
