### ISSUE TITLE
患者数（新規）がマイナス？

### ISSUE THREAD

**Issue by ietanothr** [kaz-ogiwara/covid19#52]
5/1の新規患者数が-161となっておりますが、これは正しいのでしょうか？
だとしたらどういう意味に捉えればよろしいでしょうか。

**Comment by kaz-ogiwara** [comment]
あくまでも新規の人数ですので減少に転じることはありえます。
重症者数や死亡者数と同様にお考えください。

**Comment by ietanothr** [comment]
内容は理解いたしました。私もデータの意味をよく確認せずに、現在の患者数が新規何人、累計何人だと思っていました。大変失礼致しました。しかし実際には累計で表示されるのが「現在の患者数の合計」で新規で表示されるのが「前日との変動数」なわけですね。重傷者や死亡者も同様で。しかしこれはあくまで合計ですから、（終息するとすれば）やがて減っていくわけで、累計というのはさすがに表現として如何かなと思いました。合計と日差のほうが私にはしっくりきます。厚労省の数字で、PCR検査陽性者の数と入退院死亡者の合計が１割以上ずれており、突合中との注釈に気づくまでは、入院者数が累計かと錯覚しておりましたが、あくまで現在の入院者数（合計）として掲示しているようです。
