### ISSUE TITLE
prefectures.csvの８列目にテキストが入っています。

### ISSUE THREAD

**Issue by stephenobrochta** [kaz-ogiwara/covid19#53]
お世話になっております。データをまともて頂いて、誠にありがとうございます。

８列目の行1626（４月２４日）以下、岩手県の死亡者は文字「-」として記入されているようです。行1626以上は、数字「0」になっておりますので、可能であれば全行を数字だけとして記入して頂けますでしょうか。

同じ列に、文字と数字が混ざっている場合がありましたら、全ては文字として読み込んでしまいます。

よろしくお願い致します

**Comment by kaz-ogiwara** [comment]
ご指摘ありがとうございます。
必ず数字にしなければならないルールもないので厚生労働省の表記に合わせています。

**Comment by stephenobrochta** [comment]
OK, though I don't fully understand why you'd go through the effort of curating this data and leave in the MHWL's inconsistencies. The entire reason you are doing this is to make the data more accessible to the public. So programers using your data will build in hacks to parse it. Here's an example.

```HackToFixBadDataColumn = nan(height(prefectures_csv),1);
for i = 1:height(prefectures_csv)
	if strcmp(prefectures_csv{i,8} , '-')
		HackToFixBadDataColumn(i) = 0;
	else
		HackToFixBadDataColumn(i) = str2num(cell2mat(prefectures_csv{i,8}));
	end
end
```
