### ISSUE TITLE
Change of columns in recent times

### ISSUE THREAD

**Issue by sajinh** [kaz-ogiwara/covid19#65]
Thank you for the great work in providing this data publicly. I am very grateful for your kindness. I would like to report a small issue with the data format that I experienced recently.

The file 'prefectures.csv' has changed its data contents recently. Previously the columns were: "year","month","date","prefectureNameJ","prefectureNameE","testedPositive","peopleTested","discharged","serious","deaths"

In the version that I checked today, it changed to:
year,month,date,prefectureNameJ,prefectureNameE,testedPositive,peopleTested,hospitalized,serious,discharged,deaths,effectiveReproductionNumber

This cause a bit of confusion to the user. I hope the columns used in different files can remain stable. If they change, it would be great if the fact is mentioned in the README or another appropriate file.

**Comment by kaz-ogiwara** [comment]
Yes, I changed the file structure just yesterday.
I have already updated README.md (in Japanese), and the English version will soon be updated as well.
Thank you for your patience!

**Comment by kaz-ogiwara** [comment]
Just updated README.en.md!

**Comment by sajinh** [comment]
Thanks a lot! I appreciate it very much. FYI, my analysis based on these data are at http://enformtk.u-aizu.ac.jp/jp_pcr/
