### ISSUE TITLE
summary.csvの作成方法

### ISSUE THREAD

**Issue by masa126** [kaz-ogiwara/covid19#67]
@kaz-ozawa,
日本のマスメディアは感染者数の増加を煽るだけで、データの科学的検証をしていませんが、COVID-19関連公開データからの状況可視化が素晴らしいです。

下記記事に掲載されているサンプルコードではsummary.csvを使用されていますが、dataフォルダには見当たりません。
https://blog.imind.jp/entry/2020/05/03/131718
summary.csvの作成方法を開示戴けませんか？

**Comment by kaz-ogiwara** [comment]
summary.csvは、厚生労働省がオープンデータを出していない時期の仕様です。
当初はサイト上の画像やPDFでしかデータが開示されていなかったので、元データへのアクセスを簡易にする目的でsummary.csvを生成して、毎日更新していました。
現在は厚生労働省から過去分含めたCSVファイルが更新されているので、そちらを参照するほうが早いと考えます。
（なお厚生労働省から発表されているファイルは毎日バックアップを取ってこちらのリポジトリにもアップロードしています）

**Comment by masa126** [comment]
@kaz-ozawa,
ご回答有難うございます。
厚生省さえ表示していない陽性者率、重症化率、死亡率を表示しては如何でしょうか。
dailyのPCR検査数、陽性者数、患者数、重症者数、死者数などを行列データとし、t-SNEやUMAPで2次元表示すれば、感染の第１波、２波、３波の状況を可視化できます。
